# tell it where to look
comment: false

codecov:
  notify:
    require_ci_to_pass: no

coverage:
  status:
    patch:
      default:
        target: 50%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: failure
    project:
      default: false
      library:
        target: 50%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: failure
        paths: '!tests/.*'
      tests:
        target: auto
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: failure
        paths: 'tests/.*'
