"""
Regenerate YAML summary files for the YAML-based regression tests.

Run this after an intentional change to update the expected values:

    cd <repo root>
    python tests/_generate_expected_yaml.py

Each YAML file stores per-variable statistics (min, max, mean, std, n_valid,
n_nan) and time-derivative statistics (diff_mean, diff_std), plus global and
variable-level CF attributes.  These are compared by test_*_yaml.py tests.

The script reads from the existing output NC files rather than re-running the
full pipeline, so it is fast and has no dependency on dbdreader or other
glider-specific tools.  Run the normal test suite first to ensure the NC files
are up to date, then run this script to capture the new expected values.
"""

from pathlib import Path
from shutil import copy

import numpy as np
import xarray as xr
import yaml


SKIP_ATTRS = {'date_created', 'date_issued', 'history'}


def summarize(ds: xr.Dataset) -> dict:
    result = {
        'attrs': {k: str(v) for k, v in ds.attrs.items()
                  if k not in SKIP_ATTRS},
        'variables': {},
    }
    for var in ds.variables:
        da = ds[var]
        vals = da.values

        if np.issubdtype(vals.dtype, np.datetime64):
            vals = vals.astype('datetime64[ns]').astype('float64')

        vals = vals.flatten().astype('float64')
        valid = vals[~np.isnan(vals)]
        diffs = np.diff(valid)

        entry = {
            'attrs': {k: str(v) for k, v in da.attrs.items()},
            'n_valid': int(len(valid)),
            'n_nan': int(np.sum(np.isnan(vals))),
        }
        if len(valid):
            entry.update(
                min=float(np.min(valid)),
                max=float(np.max(valid)),
                mean=float(np.mean(valid)),
                std=float(np.std(valid)),
            )
        if len(diffs):
            entry.update(
                diff_mean=float(np.mean(diffs)),
                diff_std=float(np.std(diffs)),
            )
        result['variables'][var] = entry
    return result


def write(nc_path: Path, yaml_path: Path) -> None:
    yaml_path.parent.mkdir(parents=True, exist_ok=True)
    ds = xr.open_dataset(nc_path)
    summary = summarize(ds)
    with open(yaml_path, 'w') as f:
        yaml.dump(summary, f, default_flow_style=False, allow_unicode=True,
                  sort_keys=True)
    print(f'wrote {yaml_path}')


if __name__ == '__main__':
    tests_dir = Path(__file__).parent
    expected_yaml = tests_dir / 'expected'

    # Pipeline output dirs (generated by the test suite).  Run pytest first
    # so these files are up to date, then run this script to capture the new
    # expected values.
    example_data = tests_dir / 'example-data'

    todo = {
        # --- slocum L0 timeseries ---
        example_data / 'example-slocum/L0-timeseries/dfo-rosie713-20190615.nc':
            expected_yaml / 'example-slocum/L0-timeseries/dfo-rosie713-20190615.yml',

        # --- seaexplorer NRT sub L0 timeseries ---
        example_data / 'example-seaexplorer/L0-timeseries-test/dfo-eva035-20190718.nc':
            expected_yaml / 'example-seaexplorer/L0-timeseries/dfo-eva035-20190718.yml',

        # --- seaexplorer raw delayed L0 timeseries ---
        example_data / 'example-seaexplorer-raw/L0-timeseries-test/dfo-bb046-20200908.nc':
            expected_yaml / 'example-seaexplorer-raw/L0-timeseries/dfo-bb046-20200908.yml',

        # --- slocum process_adjusted timeseries (written directly to expected/) ---
        expected_yaml / 'example-slocum/L0-timeseries/dfo-rosie713-20190615_adjusted.nc':
            expected_yaml / 'example-slocum/L0-timeseries/dfo-rosie713-20190615_adjusted.yml',

        # --- slocum process_adjusted gridfile (written directly to expected/) ---
        expected_yaml / 'example-slocum/L0-gridfiles/dfo-rosie713-20190615_grid_adjusted.nc':
            expected_yaml / 'example-slocum/L0-gridfiles/dfo-rosie713-20190615_grid_adjusted.yml',

        # --- seaexplorer process_adjusted timeseries (written directly to expected/) ---
        expected_yaml / 'example-seaexplorer/L0-timeseries/dfo-eva035-20190718_adjusted.nc':
            expected_yaml / 'example-seaexplorer/L0-timeseries/dfo-eva035-20190718_adjusted.yml',

        # --- seaexplorer process_adjusted gridfile (written directly to expected/) ---
        expected_yaml / 'example-seaexplorer/L0-gridfiles/dfo-eva035-20190718_grid_adjusted.nc':
            expected_yaml / 'example-seaexplorer/L0-gridfiles/dfo-eva035-20190718_grid_adjusted.yml',
    }

    for nc, yml in todo.items():
        if not nc.exists():
            print(f'SKIP (NC not found): {nc}')
            continue
        write(nc, yml)
