# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

import os
import subprocess

from pyglider._version import __version__

# -- Project information -----------------------------------------------------

project = 'PyGlider'
copyright = '2022-, PyGlider team'
author = 'PyGlider team'

# The full version, including alpha/beta/rc tags
release = __version__


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'numpydoc',
    'myst_parser',
    'sphinx.ext.autodoc',
    'sphinx.ext.inheritance_diagram',
    'autoapi.extension',
    'sphinx_copybutton',
]

extensions.append('sphinx.ext.intersphinx')

intersphinx_mapping = {
    'xarray': ('http://xarray.pydata.org/en/stable/', None),
    'python': ('https://docs.python.org/3/', None),
}

autoapi_dirs = ['../pyglider']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'pydata_sphinx_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_extra_path = ['_downloads']


def create_example_data_tarball(app):
    """Bundle tests/example-data into a downloadable tarball for the docs site.

    Only raw glider input files and configuration are included; pipeline-generated
    outputs (netCDF, parquet, etc.) are excluded so users process the data themselves.
    The exclusion list mirrors tests/example-data/.gitignore.
    """
    src_parent = os.path.join(app.srcdir, '..', 'tests')
    out_dir = os.path.join(app.srcdir, '_downloads')
    os.makedirs(out_dir, exist_ok=True)
    # Directories generated by the processing pipeline — excluded from the download
    generated = [
        'L0-timeseries',
        'L0-timeseries-test',
        'L0-timeseries-test-interp',
        'L0-timeseries-og10',
        'L0-gridfiles',
        'L0-gridfiles-og10',
        'L0-profiles',
        'realtime_rawnc',
        'delayed_rawnc',
        'adjusted_output',
        '.dinkumcache',
        '.github',
    ]
    # --exclude flags must come before the positional path argument
    exclude_flags = [
        '--exclude=example-data/report.json',
        '--exclude=example-data/.github',
    ]
    for name in generated:
        exclude_flags.append(f'--exclude=example-data/*/{name}')
    subprocess.run(
        ['tar', 'czf', os.path.join(out_dir, 'example-data.tar.gz')]
        + exclude_flags
        + ['-C', src_parent, 'example-data'],
        check=True,
    )


def setup(app):
    app.connect('builder-inited', create_example_data_tarball)


html_logo = '_static/PyGliderHorizontal.svg'

html_context = {
    # "github_url": "https://github.com", # or your GitHub Enterprise interprise
    'github_user': 'c-proof',
    'github_repo': 'pyglider',
    'doc_path': 'docs/',
}
html_theme_options = {
    'icon_links': [
        {
            # Label for this link
            'name': 'GitHub',
            # URL where the link will redirect
            'url': 'https://github.com/c-proof/pyglider',  # required
            # Icon class (if "type": "fontawesome"), or path to local image (if "type": "local")
            'icon': 'fab fa-github-square',
            # The type of image to be used (see below for details)
            'type': 'fontawesome',
        },
        {
            'name': 'PyPI',
            'url': 'https://pypi.org/project/pyglider',
            'icon': 'fas fa-box',
        },
        # {   "name": "conda-forge",
        #     "url": "https://anaconda.org/conda-forge/pyglider",
        #     "icon": "fas fa-box"
        # }
    ]
}
